<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <groupId>edu.rutmiit</groupId>
    <artifactId>auto-licence-rest-v0</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>auto-licence-rest-v0 [root aggregator]</name>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>candidates-api-contract</module>
        <module>auto-licence-rest</module>
        <module>medBlanks-events-contract</module>
        <module>audit-service</module>
        <module>grpc-analytics-server</module>
        <module>grpc-enrichment-client</module>
        <module>medBlanks-grpc-contract</module>
        <module>notification-service</module>
    </modules>
</project>